# Site settings
title: Movellus
email: mfaisal@movelluscircuits.com
copyright: MOVELLUS © 2016
description: > 
  Movellus provides analog solutions with the flexibility of digital designs.
  Seamless integration, reduced power consumption, small silicon area and silicon verified IP and more.
twitter_username: movellus
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.movelluscircuits.com/" # the base hostname & protocol for your site
# Build settings
markdown: kramdown
