# Site settings
title: Movellus Circuits
email: your-email@domain.com
copyright: MOVELLUS © 2015
description: > # this means to ignore newlines until "baseurl:"
  Movellus provides analog solutions with the flexibility of digital designs.
  Seamless integration, reduced power consumption, small silicon area and silicon verified IP and more.
# host: 0.0.0.0
baseurl: "/movellus/" # the subpath of your site, e.g. /blog/
url: "http://00s.github.io" # the base hostname & protocol for your site
twitter_username: movellus
# Build settings
markdown: kramdown